-- Bayah Seafood printed menu migration
-- Run once in Supabase SQL Editor to replace the current menu with the printed-menu items.
-- This does not modify orders or customer data.
delete from public.menu_items;

insert into public.menu_items (id, category, name, description, price, popular, available) values
  ('platter-small', 'platters', 'Seafood Platter Small', '8 pcs grilled prawns & mussels, 1 crab, 2 squids. Served with white or yellow rice and 2 fish fillets. Enough for 2 persons.', 129, true, true),
  ('platter-seabream', 'platters', 'Seafood Platter with Seabream', 'Grilled or fried seabream, 8 pcs grilled prawns & mussels, 1 crab, fried squids. Served with white or yellow rice and 4 fish fillets. Enough for 2 persons.', 153, true, true),
  ('platter-family', 'platters', 'Seafood Family Platter', 'A generous family platter with prawns, mussels, crab, squids, seabream, fish fillet and rice. Enough for 3 persons.', 240, true, true),
  ('platter-lobster', 'platters', 'Lobster Seafood Platter', '1 lobster, 1 seabream, 10 pcs shrimps, 10 pcs grilled mussels, 2 squids. Served with white or yellow rice. Enough for 2–4 persons.', 295, true, true),
  ('platter-medium', 'platters', 'Seafood Platter Medium', '16 pcs prawns, 3 pcs crab, fried squids, 2 pcs grilled seabream, 1 plate jaseed, 4 fish fillets and rice. Enough for 6–8 persons.', 368, false, true),
  ('platter-large', 'platters', 'Seafood Platter Large', '2 pcs lobster, 4 slices salmon, 2 plates jaseed, 2 pcs seabream, 40 pcs shrimp, 6 pcs crab, 35 pcs mussels, 6 fried squids. Served with yellow or white rice. Enough for 8–10 persons.', 840, true, true),
  ('platter-extra-large', 'platters', 'Seafood Platter Extra Large', '3 lobster, 4 pcs salmon, 3 pcs seabream, 50 pcs shrimp, 6 pcs crab, 1 kg squid, 30 pcs half shell mussels, 1 kg fish fillet, 3 pcs jaseed and fried squids. Served with yellow or white rice. Enough for 12–15 persons.', 1050, true, true),
  ('special-pasta-red', 'specials', 'Seafood Pasta – Red Sauce', 'Seafood pasta with Bayah red sauce. Printed menu price: AED 31.50 / 63.', 31.5, true, true),
  ('special-pasta-cheese', 'specials', 'Seafood Pasta with Cheese', 'Creamy seafood pasta finished with cheese. Printed menu price: AED 37 / 70.', 37, true, true),
  ('special-rice-cheese', 'specials', 'Bayah Special Rice with Cheese', 'Bayah special seafood rice with cheese. Printed menu price: AED 31.50 / 63.', 31.5, false, true),
  ('special-bucket-cajun', 'specials', 'Seafood Bucket – Cajun Sauce', 'Mixed seafood bucket tossed in Cajun sauce. Printed menu price: AED 90 / 180.', 90, true, true),
  ('special-tilapia-singari', 'specials', 'Tilapia Meals – Vegetables Singari', 'Tilapia meal with vegetables, Singari style.', 30, false, true),
  ('special-bucket-mix', 'specials', 'Seafood Bucket Mix', 'Mixed seafood bucket. Printed menu price: AED 84 / 168.', 84, true, true),
  ('special-jasheed', 'specials', 'Jasheed', 'Bayah-style seasoned seafood dish.', 37, false, true),
  ('special-seabream-singari', 'specials', 'Seabream Singari', 'Seabream prepared Singari style.', 45, false, true),
  ('special-seabass-lemon', 'specials', 'Sea Bass Grilled with Oil & Lemon', 'Grilled sea bass finished with oil and fresh lemon.', 52, true, true),
  ('special-fried-sheri', 'specials', 'Fried Sheri Meal', 'Fried sheri meal served with sides.', 44, false, true),
  ('special-prawns-meal', 'specials', 'Prawns Meal', 'Prawns meal. Printed menu price: AED 26.50 / 53.', 26.5, true, true),
  ('special-bouri-redha', 'specials', 'Bouri Grilled Redha', 'Grilled bouri prepared Redha style.', 34, false, true),
  ('special-seabass-tray', 'specials', 'Seabass Tray with Potato', 'Sea bass tray baked with potato.', 60, true, true),
  ('special-shrimp-butter-cheese', 'specials', 'Shrimp Butterfly with Cheese', 'Butterflied shrimp topped with cheese.', 42, true, true),
  ('fish-lobster-garlic', 'fish-meals', 'Lobster with Garlic', 'Lobster prepared with garlic.', 130, true, true),
  ('fish-seabream-oil-lemon', 'fish-meals', 'Seabream Grilled with Oil & Lemon', 'Grilled seabream with oil and lemon.', 47, true, true),
  ('fish-mixed-seabream', 'fish-meals', 'Mixed Mix with Sea Bream', 'Mixed seafood served with sea bream.', 108, true, true),
  ('fish-tilapia-singari', 'fish-meals', 'Tilapia Singari', 'Tilapia prepared Singari style.', 26.5, false, true),
  ('fish-lobster-red', 'fish-meals', 'Grilled Lobster with Red Sauce', 'Grilled lobster served with Bayah red sauce.', 120, true, true),
  ('fish-salmon-meal', 'fish-meals', 'Grilled Salmon Meal', 'Grilled salmon meal served with sides.', 53, true, true),
  ('soup-seafood', 'soups-salads', 'Seafood Soup', 'Bayah seafood soup.', 25, true, true),
  ('soup-cream', 'soups-salads', 'Special Soup with Cream', 'Special creamy soup.', 27, false, true),
  ('soup-zafran', 'soups-salads', 'Bayah Special Zafran Soup', 'Bayah special saffron soup.', 28, true, true),
  ('soup-tom-yum', 'soups-salads', 'Thai Tom Yum Soup', 'Thai-style spicy and sour seafood soup.', 31.5, true, true),
  ('soup-mulukhiyah', 'soups-salads', 'Mulukhiyah with Shrimp', 'Mulukhiyah prepared with shrimp.', 32, false, true),
  ('salad-hummus', 'soups-salads', 'Hummus / Tahina', 'Printed menu price: AED 10 / 15.', 10, false, true),
  ('salad-mutabel', 'soups-salads', 'Mutabel / Baba Ghanouj', 'Printed menu price: AED 10 / 15.', 10, false, true),
  ('salad-green', 'soups-salads', 'Green Salad', 'Fresh green salad. Printed menu price: AED 10 / 15.', 10, false, true),
  ('salad-tabbouleh', 'soups-salads', 'Tabbouleh', 'Fresh tabbouleh. Printed menu price: AED 15 / 20.', 15, false, true),
  ('salad-rocca', 'soups-salads', 'Rocca Salad', 'Fresh rocca salad. Printed menu price: AED 20 / 25.', 20, false, true),
  ('salad-fattoush', 'soups-salads', 'Fattoush', 'Fresh fattoush salad. Printed menu price: AED 20 / 30.', 20, false, true),
  ('starter-fish-chips', 'starters', 'Fish and Chips', 'Crispy fish and chips.', 26.5, true, true),
  ('starter-squid-chips', 'starters', 'Squid Rings & Chips', 'Crispy squid rings with chips.', 26.5, true, true),
  ('starter-shrimp-fajita', 'starters', 'Shrimp Fajita', 'Seasoned shrimp fajita.', 26.5, true, true),
  ('starter-dynamite-shrimp', 'starters', 'Dynamite Shrimp', 'Crispy shrimp with creamy spicy sauce.', 26.5, true, true),
  ('starter-seafood-tajin', 'starters', 'Seafood Tajin – Cream, Mozzarella & Zafran', 'Seafood tajin with cream, mozzarella and saffron. Printed menu price: AED 42.', 42, false, true),
  ('starter-seafood-tajin-white', 'starters', 'Seafood Tajin – White Sauce', 'Seafood tajin with white sauce. Printed menu price: AED 38.', 38, false, true),
  ('starter-shrimp-tajin-white', 'starters', 'Shrimp Tajin – Cream, Mozzarella & Zafran', 'Shrimp tajin with cream, mozzarella and saffron. Printed menu price: AED 37.', 37, false, true),
  ('starter-shrimp-tajin-red', 'starters', 'Shrimp Tajin – Red Sauce', 'Shrimp tajin with red sauce. Printed menu price: AED 32.', 32, false, true),
  ('noodles-plain', 'noodles', 'Seafood Noodles', 'Seafood noodles.', 32.5, true, true),
  ('noodles-mozzarella', 'noodles', 'Seafood Noodles with Mozzarella', 'Seafood noodles finished with mozzarella.', 37.5, true, true),
  ('rice-white', 'rice', 'White Rice', 'Steamed white rice.', 10.5, false, true),
  ('rice-sayadiya', 'rice', 'Sayadiya Rice', 'Seasoned Sayadiya rice.', 10.5, true, true),
  ('rice-bayah-yellow', 'rice', 'Bayah Yellow Rice', 'Bayah-style yellow rice.', 13, true, true),
  ('rice-shrimp', 'rice', 'Rice with Shrimp', 'Rice prepared with shrimp.', 21, true, true),
  ('drink-avocado', 'refreshments', 'Avocado', 'Fresh avocado juice. Printed menu price: AED 12.50 / 14.50.', 12.5, false, true),
  ('drink-mango', 'refreshments', 'Mango', 'Fresh mango juice. Printed menu price: AED 12.50 / 14.50.', 12.5, true, true),
  ('drink-lemon', 'refreshments', 'Lemon', 'Fresh lemon juice. Printed menu price: AED 10.50 / 12.50.', 10.5, false, true),
  ('drink-mint-lemon', 'refreshments', 'Mint Lemon', 'Fresh mint lemon. Printed menu price: AED 10.50 / 12.50.', 10.5, true, true),
  ('drink-apple', 'refreshments', 'Apple', 'Fresh apple juice. Printed menu price: AED 12.50 / 14.50.', 12.5, false, true),
  ('drink-orange', 'refreshments', 'Orange', 'Fresh orange juice. Printed menu price: AED 12.50 / 14.50.', 12.5, true, true),
  ('drink-watermelon', 'refreshments', 'Watermelon', 'Fresh watermelon juice. Printed menu price: AED 12.50 / 14.50.', 12.5, false, true),
  ('drink-pineapple', 'refreshments', 'Pineapple', 'Fresh pineapple juice. Printed menu price: AED 12.50 / 14.50.', 12.5, false, true);

-- If your database has the image_url column, existing admin image URLs are intentionally left empty.